export interface ModelInfo {
  id: string
  name: string
  provider: 'openai' | 'google' | 'deepseek' | 'anthropic' | 'xai'
  description: string
  category: 'text' | 'image' | 'video'
  isFree: boolean
  hasReasoning?: boolean
  tokenCost: number      // tokens per message (for display)
  inputPrice: number
  outputPrice: number
  contextLimit: number
  isEnabled: boolean
  isHidden?: boolean
  usageCount: number     // simulated usage count
  rating: number         // simulated rating
}

export const AI_MODELS: ModelInfo[] = [
  // === TEXT MODELS ===
  {
    id: 'chatgpt-5.4-pro',
    name: 'ChatGPT 5.4 Pro',
    provider: 'openai',
    description: 'Максимальная производительность для сложных профессиональных задач.',
    category: 'text',
    isFree: false,
    tokenCost: 120,
    inputPrice: 60,
    outputPrice: 120,
    contextLimit: 128000,
    isEnabled: true,
    usageCount: 46468,
    rating: 4.61,
  },
  {
    id: 'chatgpt-5.4',
    name: 'ChatGPT 5.4',
    provider: 'openai',
    description: 'Флагманская модель OpenAI с нативным компьютерным управлением.',
    category: 'text',
    isFree: false,
    tokenCost: 32,
    inputPrice: 15,
    outputPrice: 32,
    contextLimit: 128000,
    isEnabled: true,
    usageCount: 234940,
    rating: 4.85,
  },
  {
    id: 'chatgpt-5.3',
    name: 'ChatGPT 5.3',
    provider: 'openai',
    description: 'Текстовые модели от OpenAI.',
    category: 'text',
    isFree: false,
    tokenCost: 25,
    inputPrice: 10,
    outputPrice: 25,
    contextLimit: 128000,
    isEnabled: true,
    usageCount: 87274,
    rating: 4.53,
  },
  {
    id: 'chatgpt-5.2-pro',
    name: 'ChatGPT 5.2 Pro',
    provider: 'openai',
    description: 'Продвинутая версия с повышенной точностью и глубокой рассуждений.',
    category: 'text',
    isFree: false,
    tokenCost: 100,
    inputPrice: 50,
    outputPrice: 100,
    contextLimit: 128000,
    isEnabled: true,
    usageCount: 73166,
    rating: 4.69,
  },
  {
    id: 'chatgpt-5.2',
    name: 'ChatGPT 5.2',
    provider: 'openai',
    description: 'Мощная универсальная модель для текста, кода, аналитики и сложных задач.',
    category: 'text',
    isFree: false,
    tokenCost: 25,
    inputPrice: 10,
    outputPrice: 25,
    contextLimit: 128000,
    isEnabled: true,
    usageCount: 235002,
    rating: 4.83,
  },
  {
    id: 'claude-opus-4.5',
    name: 'Claude Opus 4.5',
    provider: 'anthropic',
    description: 'Глубокая аналитика и точные формулировки для сложных текстов.',
    category: 'text',
    isFree: false,
    tokenCost: 45,
    inputPrice: 20,
    outputPrice: 45,
    contextLimit: 200000,
    isEnabled: true,
    usageCount: 43909,
    rating: 4.90,
  },
  {
    id: 'claude-sonnet-4.5',
    name: 'Claude Sonnet 4.5',
    provider: 'anthropic',
    description: 'Баланс скорости и качества для регулярной работы.',
    category: 'text',
    isFree: false,
    tokenCost: 26,
    inputPrice: 10,
    outputPrice: 26,
    contextLimit: 200000,
    isEnabled: true,
    usageCount: 201774,
    rating: 4.65,
  },
  {
    id: 'gemini-3-pro',
    name: 'Gemini 3 Pro',
    provider: 'google',
    description: 'Мультимодальные модели от Google.',
    category: 'text',
    isFree: false,
    tokenCost: 20,
    inputPrice: 8,
    outputPrice: 20,
    contextLimit: 2000000,
    isEnabled: true,
    usageCount: 102953,
    rating: 4.84,
  },
  {
    id: 'gemini-3-flash',
    name: 'Gemini 3 Flash',
    provider: 'google',
    description: 'Мультимодальные модели от Google.',
    category: 'text',
    isFree: false,
    tokenCost: 5,
    inputPrice: 2,
    outputPrice: 5,
    contextLimit: 1000000,
    isEnabled: true,
    usageCount: 127836,
    rating: 4.91,
  },
  {
    id: 'deepseek-v3',
    name: 'DeepSeek V3',
    provider: 'deepseek',
    description: 'Самая экономичная модель для простых задач.',
    category: 'text',
    isFree: false,
    tokenCost: 3,
    inputPrice: 1,
    outputPrice: 3,
    contextLimit: 64000,
    isEnabled: true,
    usageCount: 315420,
    rating: 4.72,
  },
  {
    id: 'grok-4',
    name: 'Grok 4',
    provider: 'xai',
    description: 'Текстовые модели от xAI.',
    category: 'text',
    isFree: false,
    tokenCost: 25,
    inputPrice: 10,
    outputPrice: 25,
    contextLimit: 128000,
    isEnabled: true,
    usageCount: 223418,
    rating: 4.97,
  },

  // === VIDEO MODELS ===
  {
    id: 'kling-2.6-motion',
    name: 'Kling 2.6 Motion Control',
    provider: 'openai',
    description: 'Генерация видео с управлением движением камеры.',
    category: 'video',
    isFree: false,
    tokenCost: 170,
    inputPrice: 80,
    outputPrice: 170,
    contextLimit: 4096,
    isEnabled: true,
    usageCount: 222222,
    rating: 4.57,
  },
  {
    id: 'kling-v3-motion',
    name: 'Kling V3 Motion Control',
    provider: 'openai',
    description: 'Перенос движений с видео на изображение, улучшенное качество.',
    category: 'video',
    isFree: false,
    tokenCost: 170,
    inputPrice: 80,
    outputPrice: 170,
    contextLimit: 4096,
    isEnabled: true,
    usageCount: 296298,
    rating: 4.67,
  },
  {
    id: 'kling-2.6-text',
    name: 'Kling 2.6 (Text to Video)',
    provider: 'openai',
    description: 'Создание видео по текстовому описанию.',
    category: 'video',
    isFree: false,
    tokenCost: 250,
    inputPrice: 120,
    outputPrice: 250,
    contextLimit: 4096,
    isEnabled: true,
    usageCount: 114309,
    rating: 4.56,
  },
  {
    id: 'kling-2.6-image',
    name: 'Kling 2.6 (Image to Video)',
    provider: 'openai',
    description: 'Анимация изображений в видео.',
    category: 'video',
    isFree: false,
    tokenCost: 250,
    inputPrice: 120,
    outputPrice: 250,
    contextLimit: 4096,
    isEnabled: true,
    usageCount: 183609,
    rating: 4.92,
  },

  // === IMAGE MODELS ===
  {
    id: 'nano-banana-edit',
    name: 'Nano Banana Edit',
    provider: 'openai',
    description: 'Редактирование и улучшение готовых изображений.',
    category: 'image',
    isFree: false,
    tokenCost: 14,
    inputPrice: 5,
    outputPrice: 14,
    contextLimit: 4096,
    isEnabled: true,
    usageCount: 98441,
    rating: 4.45,
  },
]

export const DEFAULT_MODEL_ID = 'chatgpt-5.4-pro'
export const FALLBACK_MODEL_ID = 'gemini-3-flash'

export const PROVIDER_LABELS: Record<string, string> = {
  openai: 'OpenAI',
  google: 'Google',
  deepseek: 'DeepSeek',
  anthropic: 'Anthropic',
  xai: 'xAI',
}

// Legacy AIModel type alias
export type AIModel = ModelInfo
