import { AIModel } from '../types'

export const AI_MODELS: AIModel[] = [
  // Google Models
  {
    id: 'gemini-2.0-flash',
    name: 'Gemini 2.0 Flash',
    provider: 'google',
    inputPrice: 1,
    outputPrice: 2,
    contextLimit: 1000000,
    isEnabled: true,
  },
  {
    id: 'gemini-1.5-flash',
    name: 'Gemini 1.5 Flash',
    provider: 'google',
    inputPrice: 1,
    outputPrice: 2,
    contextLimit: 1000000,
    isEnabled: true,
  },
  {
    id: 'gemini-1.5-pro',
    name: 'Gemini 1.5 Pro',
    provider: 'google',
    inputPrice: 5,
    outputPrice: 10,
    contextLimit: 2000000,
    isEnabled: true,
  },
  // DeepSeek Models
  {
    id: 'deepseek-r1',
    name: 'DeepSeek R1',
    provider: 'deepseek',
    inputPrice: 2,
    outputPrice: 4,
    contextLimit: 64000,
    isEnabled: true,
  },
  {
    id: 'deepseek-v3',
    name: 'DeepSeek V3',
    provider: 'deepseek',
    inputPrice: 1,
    outputPrice: 2,
    contextLimit: 64000,
    isEnabled: true,
  },
  // OpenAI Models
  {
    id: 'o3-mini',
    name: 'o3-mini',
    provider: 'openai',
    inputPrice: 3,
    outputPrice: 6,
    contextLimit: 128000,
    isEnabled: true,
  },
  {
    id: 'o1',
    name: 'o1',
    provider: 'openai',
    inputPrice: 10,
    outputPrice: 20,
    contextLimit: 128000,
    isEnabled: true,
  },
  {
    id: 'o1-mini',
    name: 'o1-mini',
    provider: 'openai',
    inputPrice: 5,
    outputPrice: 10,
    contextLimit: 128000,
    isEnabled: true,
  },
  {
    id: 'gpt-4-turbo',
    name: 'GPT-4 Turbo',
    provider: 'openai',
    inputPrice: 10,
    outputPrice: 30,
    contextLimit: 128000,
    isEnabled: true,
  },
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    provider: 'openai',
    inputPrice: 5,
    outputPrice: 15,
    contextLimit: 128000,
    isEnabled: true,
  },
  {
    id: 'gpt-4o-mini',
    name: 'GPT-4o mini',
    provider: 'openai',
    inputPrice: 1,
    outputPrice: 2,
    contextLimit: 128000,
    isEnabled: true,
  },
  {
    id: 'gpt-4',
    name: 'GPT-4',
    provider: 'openai',
    inputPrice: 30,
    outputPrice: 60,
    contextLimit: 8192,
    isEnabled: true,
  },
  {
    id: 'gpt-3.5-turbo',
    name: 'GPT-3.5 Turbo',
    provider: 'openai',
    inputPrice: 1,
    outputPrice: 2,
    contextLimit: 16385,
    isEnabled: true,
  },
  // Hidden Placeholders (Zveno list)
  {
    id: 'claude-3-5-sonnet',
    name: 'Claude 3.5 Sonnet',
    provider: 'hidden',
    inputPrice: 3,
    outputPrice: 15,
    contextLimit: 200000,
    isHidden: true,
    isEnabled: false,
  },
  {
    id: 'claude-3-opus',
    name: 'Claude 3 Opus',
    provider: 'hidden',
    inputPrice: 15,
    outputPrice: 75,
    contextLimit: 200000,
    isHidden: true,
    isEnabled: false,
  },
  {
    id: 'mistral-large',
    name: 'Mistral Large',
    provider: 'hidden',
    inputPrice: 4,
    outputPrice: 12,
    contextLimit: 32000,
    isHidden: true,
    isEnabled: false,
  },
]

export const DEFAULT_MODEL_ID = 'gemini-1.5-flash'
export const FALLBACK_MODEL_ID = 'gpt-4o-mini'
